# Generated by Django 4.1.7 on 2023-03-24 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Printer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="printer name", max_length=64)),
                (
                    "api_key",
                    models.CharField(
                        help_text="API access key", max_length=64, unique=True
                    ),
                ),
                (
                    "check_type",
                    models.CharField(
                        choices=[("K", "kitchen"), ("C", "client")],
                        help_text="the type of check that the printer prints",
                        max_length=7,
                    ),
                ),
                (
                    "point_id",
                    models.IntegerField(
                        help_text="the point to which the printer is bound"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Check",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("K", "kitchen"), ("C", "client")],
                        help_text="check type",
                        max_length=64,
                    ),
                ),
                ("order", models.JSONField(help_text="order information")),
                (
                    "status",
                    models.CharField(
                        choices=[("N", "new"), ("R", "rendered"), ("P", "printed")],
                        help_text="check status",
                        max_length=64,
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        help_text="a link to the generated PDF file", upload_to=""
                    ),
                ),
                (
                    "printer",
                    models.ForeignKey(
                        help_text="printer",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pos_terminal.printer",
                    ),
                ),
            ],
        ),
    ]
